### ISSUE TITLE
未找到 app.json 中的定义的 pages "pages/index" 对应的 WXML 文件

### ISSUE THREAD

**Issue by jianchaoming** [ivanlee93/mpvue-cli#1]
按照基本步骤引入的，是哪里配置有问题还是包版本有问题？

**Comment by ivanlee93** [comment]
是我遗漏了，改为 "mpvue-loader": "git+https://github.com/HelloZJW/mpvue-loader.git#patch1.0.x" 即可解决

**Comment by ivanlee93** [comment]
或者重新初始化项目

**Comment by ivanlee93** [comment]
> 按照基本步骤引入的，是哪里配置有问题还是包版本有问题？

是我遗漏了，改为 "mpvue-loader": "git+https://github.com/HelloZJW/mpvue-loader.git#patch1.0.x" 或者重新初始化项目，即可解决

**Comment by jianchaoming** [comment]
感谢大神解惑
