### ISSUE TITLE
px2rpx 转码css中的px 与 style="width:100px"未被转码 导致大小设置在不同分辨率设备下 出现不一致的

### ISSUE THREAD

**Issue by qingwatianya** [ivanlee93/mpvue-cli#3]
<div style="background-color:gray">
	<div class="border">
		<img style=" **width:100px; height:100px**;" src="" alt="sdfsdf">
	</div>
</div>

//转码前
.border{
  background-color:red; 
  height: 100px;
}

//转码后： style 中的width height 在编译后依然是100**px**  导致最终在不同设备分辨下100px  和 200**rpx** 不相等  这算是一个问题吗？
.border {
  background-color: red;
  height: 200rpx;
}

要么都在style中间设置 px  要么都在css文件中使用px 转码后是没有问题的

**Comment by qingwatianya** [comment]
![image](https://user-images.githubusercontent.com/12954201/47254592-2aeb1600-d497-11e8-8922-57ebda79b93a.png)

![image](https://user-images.githubusercontent.com/12954201/47254604-4524f400-d497-11e8-8080-b24958edca9d.png)

![image](https://user-images.githubusercontent.com/12954201/47254609-48b87b00-d497-11e8-8617-28efa6e7a9da.png)

**Comment by ivanlee93** [comment]
这个建议你到官方的Code中提交Issues https://github.com/Meituan-Dianping/mpvue
