### ISSUE TITLE
你好伙计 你的框架用着确实很舒服省事儿  但是我又遇到问题了 你给看看有招没

### ISSUE THREAD

**Issue by qingwatianya** [ivanlee93/mpvue-cli#4]
项目一直都好好的  昨天添加了一个 Git版本控制 然后项目 
执行命令 npm run dev：
> rensanqian@1.0.0 dev E:\Projects_Vue\rensanqian
> node build/dev-server.js
就停在这个两行输出了 等多久都没用  IDE没卡死 CPU性功能消耗也正常  另外一个项目npm run dev 一直都是好着的 说明系统环境没问题

然后我就把当前项目 重新 vue init ivanlee93/mpvue-cli rensanqian 重新初始化一下  然后用代码版本控制 还原所有更改 恢复到初始化之前的状态  再进行  npm run dev 就编译成功了  但是等我吧VSCode 关闭 重新打开项目 编译又不行了  把Git代码控制功能取消掉也不行  中途没有任何错误  太特么诡异了 我直接给跪了 完全不知道问题在哪里

**Comment by ivanlee93** [comment]
我之前也遇到过 , 我的解决步骤:
首先把dist、node-module文件夹删除 , 重新安装依赖 , 检查所有vue文件 , script不能缺少 .
然后重新npm run dev

**Comment by ivanlee93** [comment]
> 项目一直都好好的 昨天添加了一个 Git版本控制 然后项目
> 执行命令 npm run dev：
> 
> > rensanqian@1.0.0 dev E:\Projects_Vue\rensanqian
> > node build/dev-server.js
> > 就停在这个两行输出了 等多久都没用  IDE没卡死 CPU性功能消耗也正常  另外一个项目npm run dev 一直都是好着的 说明系统环境没问题
> 
> 然后我就把当前项目 重新 vue init ivanlee93/mpvue-cli rensanqian 重新初始化一下 然后用代码版本控制 还原所有更改 恢复到初始化之前的状态 再进行 npm run dev 就编译成功了 但是等我吧VSCode 关闭 重新打开项目 编译又不行了 把Git代码控制功能取消掉也不行 中途没有任何错误 太特么诡异了 我直接给跪了 完全不知道问题在哪里

尝试把dist、node-module文件夹删除，重新装依赖，保证所有vue文件的script没有缺失，然后重新cnpm run dev

**Comment by ivanlee93** [comment]
另外，在mpvue作者没更新之前，不建议用在比较急或者稍微复杂的项目，避免遇到死胡同。原生也不错，除了一些封装没法注入，其实也挺好用，起码没坑。参考 https://github.com/ivanlee93/wxinit

**Comment by qingwatianya** [comment]
好的 谢谢！么么哒
