### ISSUE TITLE
大神我又来了  找了几个人都搞不定  只能找你帮忙了 哈哈

### ISSUE THREAD

**Issue by qingwatianya** [ivanlee93/mpvue-cli#5]
关于 v-html 的问题  我在标签中 使用 v-html  如果里面有多个标签 显示到小程序会自动换行
 <div class=" flex flex-l flex-nowrap" @click="TestClick($event)"  v-html="haha.ff">      </div>
haha:{ff:'<div><p>圣诞快乐福建省的</p>fffskldfslkdflskdf<p>你好</p></div>'},
![image](https://user-images.githubusercontent.com/12954201/47658879-c3d40c80-dbce-11e8-88be-34b0e31db57e.png)

采用flex 水平布局  不让换行 一段一段儿的标签 就重叠了：
![image](https://user-images.githubusercontent.com/12954201/47658949-e1a17180-dbce-11e8-9c41-02712ed5a520.png)

我要展示的内容 从后台获取 可能某些元素会有特殊处理 比如颜色 或者单击事件什么  做起来感觉好别扭 你有什么好的建议和思路吗？ 谢谢

**Comment by qingwatianya** [comment]
后面这个效果重叠是因为我布局设置导致的 请忽略

**Comment by ivanlee93** [comment]
我不是大神 , 也是刚写前端不久 , 你的意思是需要后端字符串类型的html标签渲染到页面上面?
另外我没用过v-html , 可以试试 https://github.com/F-loat/mpvue-wxParse 富文本解析插件

**Comment by ivanlee93** [comment]
> 后面这个效果重叠是因为我布局设置导致的 请忽略

我自己的项目用的是这个 https://www.npmjs.com/package/mpvue-wxparse2?activeTab=readme 非常简单 , 添加样式和事件都可以
