### ISSUE TITLE
大神，在根目录下的app.json里面配置tabBar,指定的vue文件会报错

### ISSUE THREAD

**Issue by webkubor** [ivanlee93/mpvue-cli#6]
https://ws3.sinaimg.cn/large/006tNbRwgy1fwqcvx442aj31dq0z6mzu.jpg

**Comment by ivanlee93** [comment]
> https://ws3.sinaimg.cn/large/006tNbRwgy1fwqcvx442aj31dq0z6mzu.jpg

测试是正常的，检查一下格式吧
{
  "pages": [],
  "window": {
    "backgroundTextStyle": "light",
    "navigationBarBackgroundColor": "#fff",
    "navigationBarTitleText": "WeChat",
    "navigationBarTextStyle": "black"
  },
  "tabBar": {
    "color": "#b6b6b6",
    "selectedColor": "#fe5655",
    "list": [{
      "pagePath": "pages/index",
      "text": "首页"
    }, {
      "pagePath": "pages/counter",
      "text": "Vuex"
    }]
  }
}
