### ISSUE TITLE
初始化后报错

### ISSUE THREAD

**Issue by gaogelucas** [ivanlee93/mpvue-cli#7]
ERROR  Failed to compile with 3 errors                                 00:41:13

These dependencies were not found:

* @/pages/index in ./node_modules/mpvue-entry/dist/pagesIndex.js
* @/pages/counter in ./node_modules/mpvue-entry/dist/pagesCounter.js
* @/packageA/logs in ./node_modules/mpvue-entry/dist/packageALogs.js

To install them, you can run: npm install --save @/pages/index @/pages/counter @/packageA/logs

**Comment by ivanlee93** [comment]
![image](https://user-images.githubusercontent.com/22174857/48390691-4071f980-e73e-11e8-95e5-1285fb6ac737.png)
检查一下NPM环境吧，我测试初始化下载，和npm run dev都正常

**Comment by shanjixiaboss** [comment]
试装了两次都这样

![image](https://user-images.githubusercontent.com/12005707/50420547-3df0dc80-0872-11e9-9516-004549ffc3d8.png)
![image](https://user-images.githubusercontent.com/12005707/50420559-4a753500-0872-11e9-88dc-fc695c61a80a.png)
