### ISSUE TITLE
不同moudle的要怎么调用

### ISSUE THREAD

**Issue by mahaoming** [ivanlee93/mpvue-cli#8]
请问不同moudle的要怎么调用
在vue中怎么调用多个模块的actions

**Comment by ivanlee93** [comment]
`methods: {
   ...mapActions('moudle1', [
      'increment1',
      'decrement1'
    ])
   ...mapActions('moudle2', [
      'increment2',
      'decrement2'
    ])
  }
`

**Comment by ivanlee93** [comment]
> 请问不同moudle的要怎么调用
> 在vue中怎么调用多个模块的actions

`methods: { 

...mapActions('moudle1', [ 'increment1', 'decrement1' ]) 

...mapActions('moudle2', [ 'increment2', 'decrement2' ])

 }

`
