### ISSUE TITLE
初始化后报错

### ISSUE THREAD

**Issue by starxg** [ivanlee93/mpvue-cli#9]
![qq 20190219170823](https://user-images.githubusercontent.com/34997494/53003085-22b4de80-3469-11e9-93e7-7af61262e7f4.png)
大神的npm多少版本呢？
我的6.4.1

**Comment by josley007** [comment]
应该是新版本的mpvue-loader的问题，我也碰到了，替换了之前版本的yarn.lock文件就好了
[yarn.zip](https://github.com/ivanlee93/mpvue-cli/files/2893633/yarn.zip)

**Comment by starxg** [comment]
当时还是没有解决啊，最后借鉴了各位大神的做了个自己的

**Comment by josley007** [comment]
我这两天新开的模板的就都靠这个lock文件来安装依赖了，也不确定这个报错是因为什么产生的，光修改mpvue-loader的版本也不够

**Comment by starxg** [comment]
也不知道啥问题，我是后端的没事学学小程序，然后知道了mpvue，遇到各种问题

**Comment by ivanlee93** [comment]
> 也不知道啥问题，我是后端的没事学学小程序，然后知道了mpvue，遇到各种问题

新版mpvue调整了构造配置。所以导致这个问题。解决方法：手动修改package.json版本号mpvue: 1.0.13，mpvue-template-compiler：1.0.13，mpvue-loader：1.1.4  记得去掉^

另外最近转uniapp写小程序了。可以到 https://github.com/ivanlee93/uni-template-vuex 看看，该封装的也封装了。

**Comment by ivanlee93** [comment]
> 我这两天新开的模板的就都靠这个lock文件来安装依赖了，也不确定这个报错是因为什么产生的，光修改mpvue-loader的版本也不够

新版mpvue调整了构造配置。所以导致这个问题。解决方法：手动修改package.json版本号mpvue: 1.0.13，mpvue-template-compiler：1.0.13，mpvue-loader：1.1.4  记得去掉^

另外最近转uniapp写小程序了。可以到 https://github.com/ivanlee93/uni-template-vuex 看看，该封装的也封装了。
